icons_format = "{icon}"

[theme]
theme = "solarized-dark"

[icons]
icons = "awesome5"

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20

[[block]]
block = "memory"
format = "$icon $mem_total_used_percents.eng(w:2) "
format_alt = "$icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "battery"
interval = 10
full_format = "$icon $percentage "
empty_format = "$icon $percentage "

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%a %Y-%m-%d %R') "

